name: make-lint

on: push

jobs:
  my-job:
    name: make-lint-job
    runs-on: ubuntu-latest
    steps:
      - name: composer-install
        uses: php-actions/composer@v5

      - name: doing the thing
        run: make lint
        working-directory: ../.
