name: make-lint

on: push

jobs:
  my-job:
    name: make-lint-job
    runs-on: ubuntu-latest
    steps:
      - name: installing phpcs
        run: apt install phpcs

      - name: doing the thing
        run: make lint
        working-directory: ../.
