name: Super-Linter
uses: github/super-linter@v3.15.5

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint:
    # Name the Job
    name: make lint job
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: doing the thing
        run: make lint
