name: make-lint

on: push

jobs:
  my-job:
    name: make-lint-job
    runs-on: ubuntu-latest
    steps:
      - name: where-tf-am-i-now-? 
        run: pwd 
      - name: doing the thing
        run: make lint
        working-directory: /home/runner/work/php-project-lvl1/php-project-lvl1/ 
       
