name: make-lint

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  make-lint:
    # Name the Job
    name: make lint job
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: doing the thing
        command: ["make lint"] 
