name: make-lint

on: 
- push
- pull_request  

jobs:
  my-job:
    name: make-lint-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2     

      - name: install-phpcs
        run: composer require "squizlabs/php_codesniffer=*"

      - name: make-lint 
        run: make lint
        working-directory: /home/runner/work/php-project-lvl1/php-project-lvl1/ 
       
